version: '3.3'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_DST=mongodb://development:messwithbestdieliketherest@mongo:27017/
  #   depends_on:
  #     - mongo
  #     - mongo-express

  mongo:
    image: mongo:5.0.3
    ports:
      - 12017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: messwithbestdieliketherest
    
  mongo-express:
    image: mongo:5.0.3
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_PASSWORD: development
      MONGO_INITDB_ROOT_USERNAME: development
      ME_CONFIG_MONGODB_URL: mongodb://development:messwithbestdieliketherest@mongo:27017/